services:
  dndbackend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - keycloak
    environment:
      - keycloak.server-url=http://keycloak:8080
      - keycloak.realm=dnd-realm
      - keycloak.client-id=dnd-client
      - keycloak.client-secret=gea5tOXxTF4X1FOkhDqLgQ29ee4SesBF
      - keycloak.admin-username=admin
      - keycloak.admin-password=admin

  mongodb:
    image: mongo:latest
    container_name: dndmongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dnddb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: dnd-keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: ["start-dev","--import-realm"]
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

  postgres:
    image: postgres:15
    container_name: dnd-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
    driver: local
  postgres-data:
    driver: local