spring.application.name=dndbackend
spring.mongodb.host=mongodb
spring.mongodb.port=27017
spring.mongodb.database=dnddb
spring.mongodb.username=admin
spring.mongodb.password=adminpassword
spring.mongodb.authentication-database=admin
#Segun como tengan el projecto de firebase cambien la ruta del bucket y el nombre del archivo json
app.firebase.bucket.name=dndimagestorage.firebasestorage.app
app.firebase.resource.fileName=/dndimagestorage-firebase-adminsdk.json
# Configuracion para subir archivos grandes
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
# Configuración Keycloak se cambia el realm, client-id y client-secret según la configuración de Keycloak
keycloak.server-url=http://localhost:8081
keycloak.realm=dnd-realm
keycloak.client-id=dnd-client
keycloak.client-secret=gea5tOXxTF4X1FOkhDqLgQ29ee4SesBF
keycloak.admin-username=admin
keycloak.admin-password=admin

# Logging Configuration
# logging.level.root=INFO
# logging.level.com.prograweb.dndbackend=DEBUG
# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n